from server.avgserver import Avg_Server
from server.fedprophet_avgserver import Fedprophet_Avg_Server
from server.kdserver import FedDF_Server,FedET_Server
from server.partial_avgserver import Partial_Avg_Server